sudo: required
services:
  - docker

before_install:
  - docker build -t edinga1/docker-react -f Dockerfile.dev .

script:
  - docker run edinga1/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-react.dev"
  bucket_name: ""
  bucket_path: ""
  on:
      branch: master
  access_key_id: "$AWS_ACCESS_KEY"
    secure: "$AWS_SECRET_KEY"